name: deploy@main
on:
    push:
        branches:
            - main
jobs:
    main:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Node ${{ matrix.node-version }}
              uses: actions/setup-node@v2.1.1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache node modules
              uses: actions/cache@v2.1.1
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - name: Install npm dependencies
              run: |
                  npm install

            - name: Build production
              run: npm run build

            - name: Deploy to Firebase@dev
              uses: w9jds/firebase-action@v1.5.0
              with:
                  args: deploy
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                  PROJECT_ID: firewit-dev
